version: '3.5'

services:
  symfony-api-platform-web:
    container_name: symfony-api-platform-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1000:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-api-platform-be
    networks:
      - symfony-api-platform-network

  symfony-api-platform-be:
    container_name: symfony-api-platform-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=symfony-api-platform
    networks:
      - symfony-api-platform-network

  symfony-api-platform-db:
    container_name: symfony-api-platform-db
    build:
      context: ./docker/database
    ports:
      - 10000:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - symfony-api-platform-db-data:/var/lib/mysql
    networks:
      - symfony-api-platform-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  symfony-api-platform-db-data:

networks:
  symfony-api-platform-network:
    external: true
