version: '3.5'

services:
  symfony-api-platform-web:
    container_name: symfony-api-platform-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1000:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-api-platform-be
    networks:
      - symfony-api-platform-network

  symfony-api-platform-be:
    container_name: symfony-api-platform-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=symfony-api-platform
    networks:
      - symfony-api-platform-network

  symfony-api-platform-db:
    container_name: symfony-api-platform-db
    build:
      context: ./docker/database
    ports:
      - 10000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - symfony-api-platform-db-data:/var/lib/mysql
    networks:
      - symfony-api-platform-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION']

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
  symfony-api-platform-db-data:

networks:
  symfony-api-platform-network:
    external: true
